#!/bin/bash 
#SBATCH --time=02:00:00
#SBATCH -p ccp20 
#SBATCH -N 2 --exclusive --ntasks-per-node 32
#SBATCH -J 2CsHgAgCl 
#SBATCH --output=log0_spins_CsHgAgCl
#SBATCH --ntasks-per-core=1 
#SBATCH --error=log0_spins_CsHgAgCl

module purge 
module load vasp/6.3.0 

ulimit -s unlimited
startingtime=$(date)
now=$(date +'%s') 
mpirun vasp_std 
endtime=$(date +'%s') 
duration=$(($endtime-$now)) 
echo 'Started on: ' $startingtime 'calculation ran for: ' $duration '[s]'
