site_name: FAIR Tool - Computational Materials Data made FAIR
site_author: Dr. Ravindra Shinde
site_url: http://127.0.0.1:8000
site_description: 'The website and the repository guides on the data management for Computational Physics and Chemistry research for a FAIR storage of raw data, processed data, and metadata.

  '
repo_name: neelravi/fairtool
repo_url: https://github.com/neelravi/fairtool
edit_uri: blob/main/documentation/docs/
copyright: 'Copyright &copy; 2025 - – Dr. Ravindra Shinde. <a href="#__consent">Change cookie settings</a>

  '
extra_css:
- stylesheets/extra.css
extra_javascript:
- js/3Dmol-min.js
- js/structure.js
theme:
  name: material
  custom_dir: material/overrides
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - content.tooltips
  - content.cards
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  palette:
  - media: (prefers-color-scheme)
    toggle:
      icon: material/weather-night
      name: Switch to light mode
    primary: green
    accent: deep orange
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: green
    accent: deep orange
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    accent: amber
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: assets/logo
  logo: assets/logo.png
plugins:
- macros:
    module_name: macros
- search:
    separator: '[\s\u200b\-_,:!=\[\]()"s/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
hooks:
- material/overrides/hooks/shortcodes.py
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  consent:
    title: Cookie consent
    description: We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better.
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/neelravi/fairtool/
  - icon: fontawesome/brands/docker
    link: https://hub.docker.com/r/neelravi/
  - icon: fontawesome/brands/python
    link: https://pypi.org/user/neelravi/
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- tables
- toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink:
    normalize_issue_symbols: true
    repo_url_shorthand: true
    user: squidfunk
    repo: mkdocs-material
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.snippets:
    auto_append:
    - includes/mkdocs.md
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
not_in_nav: '/tutorials/**/*.md

  '
nav:
- Home: index.md
- Visualizations:
  - fairtool_2:
    - Overview: fair_vis/fairtool_2.md
    - tests:
      - Overview: fair_vis/fairtool_2/tests.md
      - VASP:
        - Overview: fair_vis/fairtool_2/tests/VASP.md
        - Advanced:
          - Overview: fair_vis/fairtool_2/tests/VASP/Advanced.md
          - example04: fair_vis/fairtool_2/tests/VASP/Advanced/example04.md
          - example05: fair_vis/fairtool_2/tests/VASP/Advanced/example05.md
          - example06: fair_vis/fairtool_2/tests/VASP/Advanced/example06.md
        - Basic:
          - Overview: fair_vis/fairtool_2/tests/VASP/Basic.md
          - example01: fair_vis/fairtool_2/tests/VASP/Basic/example01.md
  - fairtool_kon2:
    - Overview: fair_vis/fairtool_kon2.md
    - tests:
      - Overview: fair_vis/fairtool_kon2/tests.md
      - VASP:
        - Overview: fair_vis/fairtool_kon2/tests/VASP.md
        - Advanced:
          - Overview: fair_vis/fairtool_kon2/tests/VASP/Advanced.md
          - example04: fair_vis/fairtool_kon2/tests/VASP/Advanced/example04.md
          - example05: fair_vis/fairtool_kon2/tests/VASP/Advanced/example05.md
          - example06: fair_vis/fairtool_kon2/tests/VASP/Advanced/example06.md
        - Basic:
          - Overview: fair_vis/fairtool_kon2/tests/VASP/Basic.md
          - example01: fair_vis/fairtool_kon2/tests/VASP/Basic/example01.md
use_directory_urls: false
